# Generated by Django 6.1.1 on 2026-09-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tope_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tramite', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_prestado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_interes', models.DecimalField(choices=[(7.5, '7.5% Quincenal'), (10.0, '10% Quincenal'), (15.0, '15% Quincenal')], decimal_places=2, default=10.0, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGO_INTERES', 'Pago de Interés'), ('ABONO_CAPITAL', 'Abono a Capital'), ('REFINANCIAMIENTO', 'Refinanciamiento')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes_atrasado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gestion.prestamo')),
            ],
        ),
    ]
