# Generated by Django 6.1.1 on 2026-09-07 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=50)),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Modificación'), ('ELIMINAR', 'Eliminación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Historial de Auditoría',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cobrar_mora',
            field=models.BooleanField(default=True, verbose_name='¿Cobrar mora por atraso?'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto_abonado_capital',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='codigo_tramite',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='porcentaje_interes',
            field=models.DecimalField(choices=[(0.0, '0% Sin Interés'), (7.5, '7.5% Quincenal'), (10.0, '10% Quincenal'), (15.0, '15% Quincenal')], decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='interes_atrasado',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('PAGO_CUOTA', 'Pago de Cuota / Abono'), ('REFINANCIAMIENTO', 'Refinanciamiento')], default='PAGO_CUOTA', max_length=30),
        ),
    ]
