# Generated by Django 6.1.1 on 2026-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_historialauditoria_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_base', models.DecimalField(decimal_places=2, default=200.0, max_digits=12, verbose_name='Capital Base Inicial')),
            ],
            options={
                'verbose_name': 'Configuración Financiera',
                'verbose_name_plural': 'Configuración Financiera',
            },
        ),
    ]
