# Generated by Django 6.1.1 on 2026-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_configuracionfinanciera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/cedulas/', verbose_name='Cédula (Parte Frontal)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula_trasera',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/cedulas/', verbose_name='Cédula (Parte Trasera)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula / ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tope_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Límite de Crédito ($)'),
        ),
    ]
