# Generated by Django 6.1.1 on 2026-09-08 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cliente_cedula_frontal_cliente_cedula_trasera_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialauditoria',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Historial de Auditoría', 'verbose_name_plural': 'Historial de Auditoría'},
        ),
        migrations.AddField(
            model_name='historialauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='historialauditoria',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='historialauditoria',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historialauditoria',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='historialauditoria',
            name='tabla',
            field=models.CharField(max_length=50, verbose_name='Módulo / Tabla'),
        ),
    ]
