# Generated by Django 6.1.1 on 2026-09-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_historialauditoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('capital_invertido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('porcentaje_retorno', models.DecimalField(decimal_places=2, help_text='Ejemplo: 10.00 para 10%', max_digits=5)),
                ('comision_gestion', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto retenido para el socio cobrador/administrador (ej. 40.00)', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeduccionSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej: Descuento gastos nieta', max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True, help_text='Marcar para aplicar en la liquidación')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='gestion.socio')),
            ],
        ),
    ]
