# Generated by Django 6.1.1 on 2026-09-15 23:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_socio_deduccionsocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Financiera La Dorada', max_length=100, verbose_name='Nombre de la Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo de la Empresa')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono / WhatsApp de Contacto')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Física')),
            ],
            options={
                'verbose_name': 'Administración de la Página',
                'verbose_name_plural': 'Administración de la Página',
            },
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='interes_atrasado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_abonado_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
