# Generated by Django 6.1.1 on 2026-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_configuracionempresa_alter_prestamo_saldo_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('PAGO_CUOTA', 'Pago de Cuota / Abono'), ('ABONO_CAPITAL', 'Abono a Capital Solo'), ('REFINANCIAMIENTO', 'Refinanciamiento')], default='PAGO_CUOTA', max_length=30),
        ),
    ]
