"""
Django settings for modulo_prestamos project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-qht-(drsfbn6+#e(#lm#1e31)h98uke2#8vo$@y**#+-&yf^&#'

DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'gestion',  # <-- Mantiene preferencia para sobreescribir templates
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'modulo_prestamos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestion.context_processors.empresa_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'modulo_prestamos.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_prestamos',
        'USER': 'postgres',
        'PASSWORD': 'Soybonito1404*',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-pa'

TIME_ZONE = 'America/Panama'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ==============================================================================
# CONFIGURACIÓN DE JAZZMIN ADMIN
# ==============================================================================
JAZZMIN_SETTINGS = {
    'site_title': 'Sistema de Préstamos',
    'site_header': 'Gestión Financiera',
    
    # Nombre de reserva/activador para que Jazzmin renderice la esquina superior
    'site_brand': 'Financiera', 
    
    'site_logo': None,
    'site_icon': None,
    'welcome_sign': 'Bienvenido al Sistema de Gestión',
    'copyright': 'Todos los derechos reservados',
    'search_model': 'gestion.Cliente',
    'topmenu_links': [
        {'name': 'Inicio', 'url': 'admin:index'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'changeform_format': 'horizontal_tabs',
    'hide_recent_actions': False,
    
    # Mantener archivos estáticos de estilización personalizada
    'custom_css': 'admin/css/custom_admin.css?v=12',
    
    'custom_links': {
        'gestion': [{
            'name': 'Reporte de Utilidades',
            'url': 'reporte_utilidades',
            'icon': 'fas fa-chart-line',
            'permissions': ['gestion.view_prestamo']
        }]
    },
    'order_with_respect_to': ['gestion', 'auth'],
}




# ==============================================================================
# PERSONALIZACIÓN DE COLORES DE LA INTERFAZ
# ==============================================================================
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-navy navbar-dark",   # Color azul marino para la barra superior
    "sidebar": "sidebar-dark-navy",        # Menú lateral a juego
    "accent": "accent-primary",
    "theme": "flatly",
    "no_navbar_border": True,
    "sidebar_fixed": True,
    "navbar_fixed": True,
}